P55. exercise 55
codechobostudy/FPIS pull request #12
Opened 2017-08-24 07:54 UTC by audtjddld

i pull request again

remove unnecessary parameter count

2017-08-25 11:04 UTC, loustler commented
@audtjddld Plz Add test code

2017-08-25 11:10 UTC, loustler commented
This PR reference by #15

2017-08-27 14:54 UTC, audtjddld commented
i do not add test code to commit. so that i retry pull request. -_-;

2017-08-27 16:17 UTC, loustler requested changes
A some errors occurs from your test code.

Please fix 

The incorrect package path which reviewed by me in this review to occur error.

2017-08-27 16:17 UTC, loustler commented on src/main/scala/com/chobostudy/audtjddld/datastructure/SolutionP55.scala
> +package com.chobostudy.loustler.datastructure
I think this package path is incorrect, right?

2017-08-27 16:17 UTC, loustler commented on src/test/scala/com/chobostudy/audtjddld/datastructure/SolutionP55Test.scala
> +package com.chobostudy.loustler.datastructure
It's too 

The package path is incorrect.

2017-08-29 07:56 UTC, audtjddld commented
i update package path and convert to gradle project.

2017-08-29 08:06 UTC, audtjddld commented
In the Eclipse IDE, it was a previously unrecognized Scala project for the git repository.
So I set up the scala project in the `.project` file and applied the gradle to add the missing `org.scalatest` library.

2017-08-29 08:07 UTC, loustler requested changes
Did you have any reason why use gradle ?

2017-08-29 08:07 UTC, loustler commented on build.gradle
> +  	testRuntime 'org.pegdown:pegdown:1.4.2'
reindent plz

2017-08-29 08:13 UTC, audtjddld commented on build.gradle
> +  	testRuntime 'org.pegdown:pegdown:1.4.2'
done

2017-08-29 08:13 UTC, audtjddld commented on build.gradle
> +  	testRuntime 'org.pegdown:pegdown:1.4.2'
missing org.scalatest library.

2017-08-29 09:11 UTC, loustler approved these changes
I'll merge it.

Review #9 plz

2017-08-29 09:11 UTC, merged